# Generated by Django 3.1.2 on 2020-11-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Autor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('PaisOrigen', models.CharField(max_length=30)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('Genero_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('Idioma_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Idioma', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Libro_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Sinopsis', models.CharField(default='Sinópsis no disponible actualmente', max_length=500, null=True)),
                ('RutaImg', models.CharField(max_length=250)),
                ('Genero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='GestionLibros.genero')),
                ('Idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionLibros.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Venta_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rut', models.CharField(max_length=9)),
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoPaterno', models.CharField(max_length=100)),
                ('ApellidoMaterno', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Libro_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionLibros.libro')),
            ],
        ),
    ]
