# Generated by Django 3.1.2 on 2020-11-14 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Cantidad_Disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='Precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='Cantidad_Venta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionLibros.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='RutaImg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Sinopsis',
            field=models.CharField(default='Sinópsis no disponible actualmente', max_length=2000, null=True),
        ),
    ]
