# Generated by Django 3.1.2 on 2020-11-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0003_auto_20201113_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='RutaImg',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
