# Generated by Django 3.1.2 on 2020-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0004_auto_20201113_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Sinopsis',
            field=models.CharField(default='Sinópsis no disponible actualmente', max_length=900, null=True),
        ),
    ]
