# Generated by Django 3.1.2 on 2020-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0005_auto_20201113_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Sinopsis',
            field=models.CharField(default='Sinópsis no disponible actualmente', max_length=2000, null=True),
        ),
    ]
