# Generated by Django 3.1.2 on 2020-11-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0002_auto_20201113_2115'),
        ('GestionLibros', '0006_auto_20201113_2100'),
    ]

    operations = [
    ]
