# Generated by Django 3.1.2 on 2020-11-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLibros', '0007_merge_20201113_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Asunto', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
